### PR TITLE
update default static path to mu_static

### PR DESCRIPTION
**Pull request by mmcgahan**
This is all that is needed to update the static path, but downstream will need to update static proxy settings for prod

### CODE REVIEW

**Comment by mattkime** [comment]
would it be worth making this configurable?

**Comment by mmcgahan** [comment]
@mattkime it is configurable - this is part of the `convict` config so the default can be overridden by a `config.{env}.json` file or an `ASSET_PATH` environment variable.

**Comment by willh-meetup** [comment]
PR looks ok. When updating `mup-web`, don't forget about: https://github.com/meetup/mup-web/blob/master/nginx_asset.conf

Longer term I do think we need to update our docs on config (maybe even just in mup-web and pro-web?).

**Comment by mmcgahan** [comment]
yeah a big config documentation effort would be good - probably consolidate that info in this repo and just cross-reference.

**Comment by mmcgahan** [comment]
https://meetup.atlassian.net/browse/WP-425 for documentation next sprint

**Pull request merged**
