### PR TITLE
Happypack

### PR DESCRIPTION
**Pull request by cranberyxl**

### CODE REVIEW

**Comment by mmcgahan** [comment]
I'll be interested in your findings - we tried out happypack a about 18 months ago and it didn't have any speed difference for us. Eager to know whether it works better now.

**Comment by cranberyxl** [comment]
Having trouble getting it working with our resolvers

**Comment by mmcgahan** [comment]
Any update on this? Should we close and come back to it in the future?

**Comment by cranberyxl** [comment]
This performs better on my laptop, but doesn't seem to on travis. I wonder if travis machines are single core?

**Comment by mmcgahan** [comment]
Should this be closed? If there's more work to be done, should it be filed in a followup? I'm interested in trying out different bundler options later in the quarter, especially Parcel

**Comment by cranberyxl** [comment]
No silver bullets here

**Pull request closed without merging**
